export const INSERT_MONEY = 'INSERT_MONEY';
export const FAILED_MONEY = 'FAILED_MONEY';
export const CHOOSE_PRODUCT = 'CHOOSE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const CHECK_STATUS = 'CHECK_STATUS';